export const GUIDANCE_BACKDROP_ENTER_DURATION = 260;
export const GUIDANCE_BACKDROP_EXIT_DURATION = 260;
export const GUIDANCE_BUBBLE_ENTER_DURATION = 220;
export const GUIDANCE_BUBBLE_EXIT_DURATION = 220;
export const GUIDANCE_BUBBLE_BACKDROP_COLOR = "rgba(0,0,0,0.68)";
export const GUIDANCE_ANCHOR_STABILITY_TOLERANCE = 1;
export const GUIDANCE_MAX_ANCHOR_MEASURE_ATTEMPTS = 10;
